complete -c vsparc -x -a pods -d 'get a list of the running pods'
complete -c vsparc -x -a logs -d 'get logs for named pod'
complete -c vsparc -x -a k8s -d 'proxy the k8s dashboard'
complete -c vsparc -x -a pgadmin -d 'proxy the pgadmin dashboard'
complete -c vsparc -x -a grafana -d 'proxy the grafana dashboard'
complete -c vsparc -x -a kmgr -d 'proxy the kafka manager'
complete -c vsparc -x -a tsdb -d 'proxy timescale'
